name: ditonton
description: "Project Ditonton for Dicoding Submission"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  
  about: 
    path: about
  core:
    path: core
  movies:
    path: movies
  tv_series:
    path: tv_series
  
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # Navigation
  go_router: ^14.6.2
  
  # Network
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  
  # Local Storage
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.0
  
  # Dependency Injection
  get_it: ^8.0.2
  
  # Functional Programming
  dartz: ^0.10.1
  
  # UI
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  
  # Utils
  rxdart: ^0.28.0
  firebase_core: ^4.7.0
  firebase_analytics: ^12.3.0
  firebase_crashlytics: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  mocktail: ^1.0.4
  build_runner: ^2.4.13
  bloc_test: ^9.1.7
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/certificates/
