// Mocks generated by Mockito 5.4.6 from annotations
// in ditonton/test/features/tv_series/domain/usecases/get_popular_tv_series_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:core/error/failures.dart' as _i5;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tv_series/domain/entities/tv_series.dart' as _i6;
import 'package:tv_series/domain/entities/tv_series_detail.dart' as _i7;
import 'package:tv_series/domain/repositories/tv_series_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TVSeriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSeriesRepository extends _i1.Mock
    implements _i3.TVSeriesRepository {
  MockTVSeriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TVSeries>>>
  getPopularTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTVSeries, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.TVSeries>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.TVSeries>>(
                    this,
                    Invocation.method(#getPopularTVSeries, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.TVSeries>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TVSeries>>>
  getTopRatedTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTVSeries, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.TVSeries>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.TVSeries>>(
                    this,
                    Invocation.method(#getTopRatedTVSeries, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.TVSeries>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TVSeries>>>
  getOnTheAirTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getOnTheAirTVSeries, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.TVSeries>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.TVSeries>>(
                    this,
                    Invocation.method(#getOnTheAirTVSeries, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.TVSeries>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.TVSeriesDetail>> getTVSeriesDetail(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTVSeriesDetail, [id]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.TVSeriesDetail>>.value(
                  _FakeEither_0<_i5.Failure, _i7.TVSeriesDetail>(
                    this,
                    Invocation.method(#getTVSeriesDetail, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.TVSeriesDetail>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TVSeries>>>
  getTVSeriesRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTVSeriesRecommendations, [id]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.TVSeries>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.TVSeries>>(
                    this,
                    Invocation.method(#getTVSeriesRecommendations, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.TVSeries>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TVSeries>>> searchTVSeries(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchTVSeries, [query]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.TVSeries>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.TVSeries>>(
                    this,
                    Invocation.method(#searchTVSeries, [query]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.TVSeries>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> saveWatchlist(
    _i7.TVSeriesDetail? tvSeries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveWatchlist, [tvSeries]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#saveWatchlist, [tvSeries]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> removeWatchlist(
    _i7.TVSeriesDetail? tvSeries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [tvSeries]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#removeWatchlist, [tvSeries]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isAddedToWatchlist, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TVSeries>>>
  getWatchlistTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTVSeries, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.TVSeries>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.TVSeries>>(
                    this,
                    Invocation.method(#getWatchlistTVSeries, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.TVSeries>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.SeasonDetail>> getSeasonDetail(
    int? tvId,
    int? seasonNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSeasonDetail, [tvId, seasonNumber]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.SeasonDetail>>.value(
                  _FakeEither_0<_i5.Failure, _i7.SeasonDetail>(
                    this,
                    Invocation.method(#getSeasonDetail, [tvId, seasonNumber]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.SeasonDetail>>);
}
